#!/bin/bash

# Prints out battery percentage

# CHARGING_ICON=' '
# WARNING_ICON=' '
# BATTERY_FULL_ICON=' '
# BATTERY_2_ICON=' '
# BATTERY_3_ICON=' '
# BATTERY_4_ICON=' '
CHARGING_ICON='(CHR)'
WARNING_ICON='(WAR)'
BATTERY_FULL_ICON='(BAT)'
BATTERY_2_ICON='(BAT)'
BATTERY_3_ICON='(BAT)'
BATTERY_4_ICON='(BAT)'

FULL_AT=98

BAT_ICON=""
ICON=""

get_battery()
{
	# The vast majority of people only use one battery.

	if [ -d /sys/class/power_supply/BAT1 ]; then
		capacity=$(cat /sys/class/power_supply/BAT1/capacity)
		charging=$(cat /sys/class/power_supply/BAT1/status)

		if [[ "$charging" == "Charging" ]]; then
			BAT_ICON="$CHARGING_ICON"
		elif [[ $capacity -ge $FULL_AT ]]; then
			BAT_ICON=$BATTERY_FULL_ICON
		elif [[ $capacity -le 25 ]]; then
			BAT_ICON="$WARNING_ICON"
		elif [[ $capacity -le 60 ]]; then
			BAT_ICON=$BATTERY_3_ICON
		elif [[ $capacity -le $FULL_AT ]]; then
			BAT_ICON=$BATTERY_2_ICON
		fi
	fi
	echo "$BAT_ICON $capacity%"
}

get_battery
